### ISSUE TITLE
样式没有引入

### ISSUE THREAD

**Issue by yangfei19881024** [cookiepool/cookie-ui#1]
你好，看了您的项目，很有启发，但是在npm i vue-cookie-ui 后，在项目中使用，发现没有样式。

**Comment by cookiepool** [comment]
我这边没有问题，请确保你的相关依赖安装完全，如果有条件的话最好挂代理下载npm上的包，不到万不得已不要使用cnpm。

**Comment by yangfei19881024** [comment]
谢谢，已经解决
